# server {
#     listen 80;

#     location /users {
#         proxy_pass http://user-service:8081/users;
#     }

#     location /orders {
#         proxy_pass http://order-service:8082/;
#     }
# }
# Define rate limiting zone (this is valid at http level, but allowed in conf.d)
limit_req_zone $binary_remote_addr zone=users_limit:10m rate=1r/s;

server {
    listen 80;

    location /users {
        limit_req zone=users_limit burst=10 nodelay;
        proxy_pass http://user-service:8081/users;
    }

    location /orders {
        limit_req zone=users_limit burst=10 nodelay;
        proxy_pass http://order-service:8082/;
    }
}
